# This is a basic workflow to help you get started with Actions

name: Github Action 42Crunch REST API Static Security Testing

on: push

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: 42Crunch/api-security-audit-action@v2
      with:
        api-token: ${{ secrets.API_TOKEN }}
        min-score: 75
        log-level: DEBUG
        json-report: report.json
        share-everyone: READ_WRITE
