# This is a basic workflow to help you get started with Actions

name: Github Action 42Crunch REST API Static Security Testing

on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - uses: 42Crunch/api-security-audit-action@v3
    # - uses: didushko/api-security-audit-action@master
    #   with:
    #     api-token: ${{ secrets.API_TOKEN }}
    #     platform-url: https://platform.dev.42crunch.com
    #     min-score: 75
    #     # root-directory: MyApi/testDir
    #     log-level: DEBUG
    #     json-report: report.json
    #     # sarif-report: sarif.sarif
    #     audit-timeout: 6
    #     upload-to-code-scanning: true

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: sarif-report
    #     path: MyApi/testDir/sarif.sarif

    # - uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     # Path to SARIF file relative to the root of the repository
    #     sarif_file: MyApi/testDir/sarif.sarif
    #     # Optional category for the results
    #     # Used to differentiate multiple results for one commit
    #     category: my-analysis-tool


    # - uses: didushko/42CrunchConformanceScanAction@v2
    #   with:
    #     api-token: ${{ secrets.API_TOKEN }}
    #     platform-url: https://platform.dev.42crunch.com
    #     command: xliic_scan json-report convert-to-sarif $report_path $sarif_path
    #     report-path: report.json
        
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: sarif-report
    #     path: sarif.json

    - uses: 42Crunch/api-conformance-scan-action/check-sqg@Multiactions
      if: always()
      with:
        api-token: ${{ secrets.API_TOKEN }}
        platform-url: https://platform.dev.42crunch.com
        # audit-report-path: report.json
        api-ids: e0128c1f-dfc3-4dfe-9206-c9b2c9b9071f, c6766392-a263-4f07-8461-7da1f3e24a17

    # - uses: 42Crunch/api-conformance-scan-action/convert-to-sarif@v1
    #   with:
    #     api-token: ${{ secrets.API_TOKEN }}
    #     platform-url: https://platform.dev.42crunch.com
    #     report-path: report.json
    #     sarif-path: report-scan.sarif
# 
  # upload:
  #   runs-on: ubuntu-latest
  #   needs: audit
  #   steps:
  #   - uses: github/codeql-action/upload-sarif@v2
  #     with:
  #       # Path to SARIF file relative to the root of the repository
  #       sarif_file: sarif.json
  #       # Optional category for the results
  #       # Used to differentiate multiple results for one commit
        # category: my-analysis-tool
