# This is a basic workflow to help you get started with Actions

name: Github Action 42Crunch REST API Static Security Testing

on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - uses: 42Crunch/api-security-audit-action@v3
    # - uses: didushko/api-security-audit-action@master
    #   with:
    #     api-token: ${{ secrets.API_TOKEN_PROM }}
    #     # platform-url: https://platform.dev.42crunch.com
    #     min-score: 75
    #     # root-directory: MyApi/testDir
    #     log-level: DEBUG
    #     # json-report: report.json
    #     # sarif-report: sarif.sarif
    #     audit-timeout: 6
    #     # upload-to-code-scanning: true

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: sarif-report
    #     path: MyApi/testDir/sarif.sarif

    # - uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     # Path to SARIF file relative to the root of the repository
    #     sarif_file: MyApi/testDir/sarif.sarif
    #     # Optional category for the results
    #     # Used to differentiate multiple results for one commit
    #     category: my-analysis-tool


    # - uses: didushko/42CrunchConformanceScanAction@v2
    #   with:
    #     api-token: ${{ secrets.API_TOKEN }}
    #     platform-url: https://platform.dev.42crunch.com
    #     command: xliic_scan json-report convert-to-sarif $report_path $sarif_path
    #     report-path: report.json
        
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: sarif-report
    #     path: sarif.json

    - uses: 42Crunch/cicd-github-actions/scan@master
      with:
        api-token: ${{ secrets.API_TOKEN_PROM }}
        audit-report-path: report.json
        api-ids: |
         a59d38b4-580a-42ee-9b64-1e5421d87567
         ec021be8-c40d-4351-84da-d628c251dc28
        # convert-to-sarif: sarif.sarif
        upload-sarif: true
        check-sqg: true