# This is a basic workflow to help you get started with Actions

name: Github Action 42Crunch REST API Static Security Testing

on: push

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: didushko/api-security-audit-action@write_sarif
      with:
        api-token: ${{ secrets.API_TOKEN }}
        platform-url: https://platform.dev.42crunch.com
        min-score: 75
        log-level: DEBUG
#         json-report: report.json
        sarif-report: asd/afasf/asdf
    # - uses: didushko/42CrunchConformanceScanAction@v2
    #   with:
    #     api-token: ${{ secrets.API_TOKEN }}
    #     platform-url: https://platform.dev.42crunch.com
    #     command: xliic_scan json-report convert-to-sarif $report_path $sarif_path
    #     report-path: report.json
        
#     - uses: actions/upload-artifact@v2
#       with:
#         name: sarif-report
#         path: sarif.json
        
#     - uses: github/codeql-action/upload-sarif@v2
#       with:
#         # Path to SARIF file relative to the root of the repository
#         sarif_file: sarif.json
#         # Optional category for the results
#         # Used to differentiate multiple results for one commit
#         category: my-analysis-tool

    # - uses: didushko/42CrunchConformanceScanAction@v2
    #   with:
    #     api-token: ${{ secrets.API_TOKEN }}
    #     platform-url: https://platform.dev.42crunch.com
    #     report-path: report.json
