# This is a basic workflow to help you get started with Actions

name: Github Action 42Crunch REST API Static Security Testing

on: push

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - uses: actions/upload-artifact@v2
      with:
        name: sarif-report
        path: report.sarif
        
    - uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: report.sarif
        # Optional category for the results
        # Used to differentiate multiple results for one commit
        category: my-analysis-tool
